### ISSUE TITLE
Implement Coordinator actor and Rete mocks

### ISSUE THREAD

**Issue by istvanrath** [FTSRG/incqueryd#43]
* implement skeletons for the Coordinator actor and Rete node actors
* implement integration tests covering START, CHECK, STOP lifecycle operations so that
  * Coordinator is the actual implementation
  * Rete nodes are mocks

**Comment by szarnyasg** [comment]
The estimations are described in:
1. https://github.com/FTSRG/incqueryd/tree/master/hu.bme.mit.incqueryd.allocation.csp/src/hu/bme/mit/incqueryd/csp/util/data
2. https://tdk.bme.hu/VIK/DownloadPaper/Inkrementalis-lekerdezesek-optimalizacioja-a p. 34

**Comment by thSoft** [comment]
Subscription algorithm: https://git.inf.mit.bme.hu/w?p=projects/incqueryd/incqueryd-docs.git;a=blob;f=presentations/internal/rete-recipe-deployment.pptx;h=ee015e363331bd396b2d699f9b89cca8fdd1e6c8;hb=HEAD

**Comment by thSoft** [comment]
Resolved in 4b7fb34
