### ISSUE TITLE
Migrate to new Akka version

### ISSUE THREAD

**Issue by istvanrath** [FTSRG/incqueryd#44]
Preparatory tasks:
* migrate to Akka (2.3.x)
* check how node discovery can be implemented in a straightforward way (how each actor nodes can be made aware of the addresses of the members of the Rete network)
* check exception handling best practices (i.e. the Coordinator actor should be a supervisor of Rete nodes)

**Comment by thSoft** [comment]
Using akka with docker:
https://groups.google.com/d/msg/akka-user/kmNexxCRTe4/sMM2NYZCsEkJ
http://doc.akka.io/docs/akka/snapshot/additional/faq.html#Why_are_replies_not_received_from_a_remote_actor_
