### ISSUE TITLE
Termination protocol & transaction consistency

### ISSUE THREAD

**Issue by thSoft** [FTSRG/incqueryd#45]
* see related work ([Gaben's thesis](http://home.mit.bme.hu/~bergmann/publications/bergmann_diploma_2008.pdf), 4.3-4.4)
* propagate transaction id
* determine transaction fixpoint with termination protocol
* notify listeners on transaction fixpoint

**Comment by szarnyasg** [comment]
Termination protocol by Gabor Szarnyas:
* https://git.inf.mit.bme.hu/w?p=projects/incqueryd/incqueryd-docs.git;a=tree;f=presentations/MODELS, sl12
* https://inf.mit.bme.hu/research/publications/superscalable-modeling

**Comment by bergmanngabor** [comment]
Most így újraolvasva a diplomám megfelelő részét, az én megoldásomnak jelenleg egy gyengesége az, hogy a trafó által végzett minden update esetén kell egy atomi művelet az érintett input csomópont és egy központi koordinátor között szinkronizálva. Ez elosztott esetben elég kellemetlen lehet. 

A megoldás valószínűleg olyasmi, hogy ami a központi koordinátor ("network object") volt a diplomámban, annak a logikának egy része a kliensnél lakhat. Amikor a kliens megkérdezi a koordinátort, hogy konzisztensek-e már az eredmények, akkor ezzel egy csapásra át tudja adni a nála tárolódó terminálási kritériumot - így nem kell minden elemei tuple update-nél a koordinátorhoz fordulni, csak később, query végrehajtásonként egyszer. De ezt a módosítást még át kell gondolni.

**Comment by thSoft** [comment]
The two approaches are:
* "initialize-pull": coordinator initalizes input nodes, waits termination from all of them, then pulls production node
* "reactive": every node sends its current state to both new subscribers when they subscribe and all subscribers when the state changes; a state is consistent when every node involved in the transaction update propagation has sent its new state

**Comment by thSoft** [comment]
Replace java.util.stack with scala.collection.immutabl.List.

**Comment by thSoft** [comment]
Change behavior:
* When sending "Load data" request to the coordinator, it should make input nodes load themselves and wait for them to complete.
* Rete nodes should send their current state on subscription.
* Termination protocol should also run in the subscription phase: when an input node receives a subscription message, it should increase its pending count; when it receives a termination messag, it should decrease it.
