### ISSUE TITLE
Check dashboard technologies

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/incqueryd#48]

**Comment by szarnyasg** [comment]
Investigate Neo4j rabbithole: https://github.com/neo4j-contrib/rabbithole

**Comment by thSoft** [comment]
See the return type of Coordinator.loadData. It can be serialized with [upickle](https://github.com/lihaoyi/upickle).

**Comment by szarnyasg** [comment]
The backend should be an enterprise messaging (pub-sub) technology.

The JVM should be monitored via JMX on the message bus, Rete-specific metrics should also be travelling through the message bus . The monitoring runs in Docker as well.

Frontend: check rabbithole (see above).

The coordinator should be able to publish its internal state on the bus. The discovery of the bus should work in Docker.
