### ISSUE TITLE
Use ZooKeeper for Rete node identification

### ISSUE THREAD

**Issue by thSoft** [FTSRG/incqueryd#54]
Instead of sending YellowPages and storing Subscribers.

**Comment by thSoft** [comment]
Part of #56

**Comment by thSoft** [comment]
* Implement YellowPagesUtils.findActorUsingZooKeeper
* Make ReteActorKey.apply return a key that only depends on the RdfType in case of TypeInputRecipe

**Comment by pappist** [comment]
After deserializing an ActorRef its path.address element will be null and thus it will be unusable. I tried the following deserialization methods: JavaSerializer, restore with actorSystem.provider.resolveActorRef or actorSystem.actorSelection. Serialize and deserialize an ActorPath works fine.

**Comment by thSoft** [comment]
* Remove yellowPages parameter of ReteActor.establishSubscriptions and methods of YellowPagesUtils
* Rename YellowPagesUtils to ActorLookup or similar

**Comment by pappist** [comment]
The solution is used and tested in the integration test. So this issue closed via [077c42f](https://github.com/FTSRG/incqueryd/commit/077c42f4ee7d113731bf523c8bc265fd1654e1aa)
