### ISSUE TITLE
Run Rete nodes with Hadoop+YARN

### ISSUE THREAD

**Issue by thSoft** [FTSRG/incqueryd#56]
Modified workflow:
- Start Coordinator AM
- Coordinator.loadData
  - Start Input Nodes AM
- Coordinator.startQuery
  - Start Query Nodes AM
- Coordinator.stopQuery
  - Unregister Query Nodes AM
- Unregister Coordinator AM

**Comment by thSoft** [comment]
Depends on #54

**Comment by pappist** [comment]
Workflow modification: start new ApplicationMaster per node type (coordinator / input / other (rete)) instead of starting a new instance per node.

**Comment by pappist** [comment]
Next todo: Configure ActorServiceApplication's ports to avoid port conflict inside docker containers.

**Comment by pappist** [comment]
Currently, the integration test is running according to the modified workflow:

I. System workflow:
	1. Start a YARN application to run ActorSystems
		Start one 'incqueryd' ActorSystem per YARN node with a common application master (ActorSystemsApplicationMaster)
	2. Deploy CoordinatorActor to one of the ActorSystems - the selection is made by YARN (II.)
	3. Coordinator.loadData
		- Deploy and start input ReteActors (II.)
	4. Coordinator.startQuery
		- Deploy and start query ReteActors (II.)
	5. Coordinator.stopQuery
		- Stop query ReteActors
	6. Stop ActorSystems application
		- Stop input ReteActors and CoordinatorActor
		- Unregister ActorSystemsApplicationMaster

II. ReteActor deployment workflow:
	1. Start a YARN application for Actor deployment
		- Start an instance of ActorApplicationMaster which runs an ActorApplication instance
		- The node selection (for the containers) is made by YARN - depends on the current resource usage
	2. The ActorApplication deploy the ReteActor into the ActorSystem which is running on the same node
	3. Stop the ActorApplication and unregister ActorApplicationMaster
