### ISSUE TITLE
Use DNS instead of /etc/hosts

### ISSUE THREAD

**Issue by thSoft** [FTSRG/incqueryd#57]
Currently, the identification of the cluster nodes by host name is solved by writing into /etc/hosts on every node as well as the host machine, which is is risky to run on a CI server. Solve the identification with a DNS instead.

**Comment by pappist** [comment]
DNSMASQ is installed and configured in the cluster. Run *register_cluster_dns.sh* to use it from the host/client.

**Comment by thSoft** [comment]
`scripts/test.sh` fails at:

```
Step 61 : ADD dnsmasq.conf /etc/dnsmasq.conf
INFO[0002] dnsmasq.conf: no such file or directory 
```

**Comment by pappist** [comment]
Fixed it.

**Comment by thSoft** [comment]
Works properly, thanks.
