### ISSUE TITLE
Modify workflow for performance test

### ISSUE THREAD

**Issue by thSoft** [FTSRG/incqueryd#65]
Modify the integration test workflow steps to the following so that deployment time can be excluded from the measurement:
1. Deploy input Rete nodes
1. Deploy other Rete nodes
1. Load initial data & propagate state
1. (Change data & propragate state)

**Comment by pappist** [comment]
Closed via [f118ff](https://github.com/FTSRG/incqueryd/commit/f118ffa675725d414934a90079c26be3cee30b06)
