### ISSUE TITLE
Enable remote debugging in ActorSystemApplications

### ISSUE THREAD

**Issue by pappist** [FTSRG/incqueryd#67]
The goal is to make it possible to debug ReteActors remotely. To achieve this:
1. Enable remote debugging when an ActorSystemApplication starts on a yarn node. (debug port e.g. 9999)
2. Let it be possible to connect from Eclipse with Remote Java Application debug configuration

**Comment by pappist** [comment]
Closed via [518513e](https://github.com/FTSRG/incqueryd/commit/518513e325341d82563e1b17a8de1eb948ca8923)

**Comment by thSoft** [comment]
Awesome! Please include the remote debugging settings in an Eclipse launch config or here: https://github.com/FTSRG/incqueryd/wiki/Contribute
