### ISSUE TITLE
Make dashboard runnable/debuggable from Eclipse

### ISSUE THREAD

**Issue by thSoft** [FTSRG/incqueryd#87]

**Comment by thSoft** [comment]
Unfortunately, as of 551a335ef8d997e234ae9e52d6f119b1f78798cc, I get a HTTP 500 error if I run the dashboard with Tomcat in Eclipse: ```java.lang.NoClassDefFoundError: com/vaadin/server/VaadinServlet``` I think ```ivy.xml``` is missing. Could you please try to recreate the project as described [here](https://vaadin.com/book/-/page/getting-started.first-project.html)?

**Comment by pappist** [comment]
Please try to add maven dependencies in Project properties -> Deployment Assembly.

**Comment by thSoft** [comment]
Unfortunately, as of 551a335ef8d997e234ae9e52d6f119b1f78798cc, I get a HTTP 500 error if I run the dashboard with Tomcat in Eclipse: ```java.lang.NoClassDefFoundError: com/vaadin/server/VaadinServlet``` I think ```ivy.xml``` is missing. Could you please try to recreate the project as described [here](https://vaadin.com/book/-/page/getting-started.first-project.html)?

**Comment by thSoft** [comment]
The project has problems now:
```Invalid classpath publish/export dependency /hu.bme.mit.incqueryd.yarn. Project entries not supported.```
and when I try to run the demo dashboard, I get ```com.vaadin.server.ServiceException: java.lang.NoClassDefFoundError: hu/bme/mit/incqueryd/yarn/IncQueryDZooKeeper$```.

**Comment by pappist** [comment]
The solution: It is neccessary to (re-)add the dependent projects as well to the deployment assemblies.

**Comment by thSoft** [comment]
Please write about running & debugging the dashboard both from Eclipse & command line [here](https://github.com/FTSRG/incqueryd/wiki/Contribute).
